services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:    
      - HTTP_HOST=0.0.0.0
      - POSTGRES_PASSWORD=qwerty
      - SIGNING_KEY=qwerty
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}         
      POSTGRES_PASSWORD: ${DB_PASSWORD:-qwerty}  
      POSTGRES_DB: ${DB_NAME:-postgres}            
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: