http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
postgres:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
hasher:
  cost: 10
auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 720h